spring:
  application:
    name: ingredient_service
  datasource:
    url: jdbc:mysql://localhost:3306/ingredient
    username: root
    password: Vuonga5k54tt1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
aws:
  access:
    key:
      id: AKIAQLSIVKBKPPIUZK4Q
  secret:
    access:
      key: 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
  s3:
    region: ap-southeast-1
    bucket: recipe-nqv
  default_avatar_url: hihi
  default_recipe_url: hihi
server:
  port: 8081
app:
  recipe: http://localhost:8082
