spring:
  application:
    name: ingredient_service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
aws:
  access:
    key:
      id: ${AWS_ACCESS_KEY_ID}
  secret:
    access:
      key: ${AWS_SECRET_ACCESS_KEY}
  s3:
    region: ${AWS_S3_REGION}
    bucket: ${AWS_S3_BUCKET}
  default_avatar_url: ${DEFAULT_AVATAR_URL}
  default_recipe_url: ${DEFAULT_RECIPE_URL}
server:
  port: 8080
app:
  recipe: http://localhost:8082
