server:
  port: 8888

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth_service
          uri: http://localhost:8080
          predicates:
            - Path=/**
#          filters:
#            - StripPrefix=1 # cắt bỏ 1 phần tử đầu tiên của url
        - id: profile_service
          uri: http://localhost:8084
          predicates:
            - Path=/profile/users/**
          filters:
            - StripPrefix=1